### ISSUE TITLE
2.0.1 still points to 1.3? 

### ISSUE THREAD

**Issue by 304NotModified** [tweego/JeeGooContext#1]
The files in the folder 'jeegoocontext' are still on version 1.3.

See 
https://github.com/tweego/JeeGooContext/blob/2.0.1/jeegoocontext/jquery.jeegoocontext.js
https://github.com/tweego/JeeGooContext/commits/2.0.1/jeegoocontext/jquery.jeegoocontext.js

Cheers, Julian

**Comment by tweego** [comment]
Hoi Julian,

Fixed. Thanks.

Peter
